name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    if: |
      !contains(github.event.head_commit.message, 'update submodule') &&
      !contains(github.event.head_commit.message, 'chore: update submodules') &&
      !contains(github.event.head_commit.message, 'Auto Update Submodules')

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Write key
      run: |
        echo KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }} > signing.properties
        echo KEYSTORE_ALIAS=${{ secrets.KEYSTORE_ALIAS }} >> signing.properties
        echo KEYSTORE_ALIAS_PASSWORD='${{ secrets.KEYSTORE_ALIAS_PASSWORD }}' >> signing.properties
        echo KEYSTORE_FILE=../key.jks >> signing.properties
        echo ${{ secrets.KEYSTORE }} | base64 --decode > key.jks

    - name: Build Debug
      run: ./gradlew assembleUniversalDebug

    - name: Build Release
      run: ./gradlew assembleUniversalRelease

    - name: Upload a Debug Artifact
      uses: actions/upload-artifact@v4
      with:
        name: rvxp-ci-debug-apk
        path: app/build/outputs/apk/universal/debug

    - name: Upload a Release Artifact
      uses: actions/upload-artifact@v4
      with:
        name: rvxp-ci-release-apk
        path: |
          app/build/outputs/apk/universal/release
          app/build/outputs/mapping/universalRelease/mapping.txt

    - name: Create AutoBuild Release
      run: |
        GIT_DESCRIBE=$(git rev-parse --short HEAD)
        cd app/build/outputs/apk/universal/release/
        mv app-universal-release.apk ReVancedXposed-${GIT_DESCRIBE}.apk
        gh release delete autobuild --yes || true
        gh release create autobuild ReVancedXposed-${GIT_DESCRIBE}.apk --prerelease --title "AutoBuild ${GIT_DESCRIBE}"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
