name: Auto Update Submodules

on:
  schedule:
    - cron: "0 3 * * *"   # chạy mỗi ngày lúc 3h sáng UTC
  workflow_dispatch:       # cho phép chạy thủ công

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true
          fetch-depth: 0

      - name: Update submodules to latest commit
        run: |
          git submodule update --remote --merge

      - name: Commit & push changes if any
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "chore: update submodules to latest commit"
            git push
          else
            echo "✨ No updates found"
          fi
